version: '3.8'

services:
  api:
    image: youtube-tunnel-api:${IMAGE_TAG}
    container_name: yt-api
    networks:
      - yt-network
      - proxy
      - sunflower_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yt-api.rule=Host(`yt.sonbn.xyz`) && PathPrefix(`/api`)"
      - "traefik.http.routers.yt-api.entrypoints=websecure"
      - "traefik.http.routers.yt-api.tls.certresolver=le"
      - "traefik.http.services.yt-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.yt-api.priority=20"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.yt-api.middlewares=api-strip"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      YOUTUBE_HOST: ${YOUTUBE_BASE_HOST}
      REDIS_HOST: yt-redis
      REDIS_PORT: "6379"
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: us-east-1
      MINIO_ENDPOINT: ${MINIO_API_DOMAIN}
    expose:
      - "8080"

  worker:
    image: youtube-tunnel-worker:${IMAGE_TAG}
    container_name: worker
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8081
      REDIS_HOST: yt-redis
      REDIS_PORT: "6379"
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: us-east-1
      MINIO_ENDPOINT: ${MINIO_CONTAINER_NAME}:9000
    networks:
      - yt-network
      - sunflower_data
    expose:
      - "8081"

  web:
    image: youtube-tunnel-web:${IMAGE_TAG}
    container_name: yt-web
    networks:
      - yt-network
      - proxy
      - sunflower_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yt-web.rule=Host(`yt.sonbn.xyz`)"
      - "traefik.http.routers.yt-web.entrypoints=websecure"
      - "traefik.http.routers.yt-web.tls.certresolver=le"
      - "traefik.http.services.yt-web.loadbalancer.server.port=80"
      - "traefik.http.routers.yt-web.priority=10"
    expose:
      - "80"

networks:
  yt-network:
    external: true
  proxy:
    external: true
  sunflower_data:
    external: true
